import { Category, FoodItem, RestaurantDetails } from './types';

export const DEFAULT_RESTAURANT: RestaurantDetails = {
  name: "Red Fire Grill",
  city: "Downtown Metro",
  phone: "9876543210",
  address: "123 Meat Street, Carnivore Lane",
  opensAt: "11:00",
  closesAt: "23:00"
};

export const INITIAL_MENU: FoodItem[] = [
  {
    id: '1',
    name: 'Chicken Dum Biryani',
    category: Category.BIRYANI,
    price: 249,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    description: 'Aromatic basmati rice cooked with tender chicken pieces and authentic spices.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    discount: 10
  },
  {
    id: '2',
    name: 'Mutton Rogan Josh',
    category: Category.GRAVY,
    price: 349,
    image: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?auto=format&fit=crop&w=800&q=80',
    description: 'Traditional Kashmiri style mutton curry with rich red gravy.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '3',
    name: 'Chicken 65',
    category: Category.STARTERS,
    price: 199,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
    description: 'Spicy, deep-fried chicken dish originating from Hotel Buhari.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Spicy',
    discount: 5
  },
  {
    id: '4',
    name: 'Pepper Chicken Fry',
    category: Category.FRIED,
    price: 219,
    image: 'https://images.unsplash.com/photo-1606728035253-49e8a23146de?auto=format&fit=crop&w=800&q=80',
    description: 'Dry chicken roast with freshly ground black pepper.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Medium'
  },
  {
    id: '5',
    name: 'Egg Chicken Roll',
    category: Category.ROLLS,
    price: 99,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80',
    description: 'Flaky paratha wrapped with egg and spicy chicken filling.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Mild'
  },
  {
    id: '6',
    name: 'Family Combo Feast',
    category: Category.COMBOS,
    price: 999,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    description: '2 Biryanis, 1 Starter, 2 Cokes. Perfect for 2-3 people.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Medium',
    discount: 25
  },
  {
    id: '7',
    name: 'Hyderabadi Mutton Biryani',
    category: Category.BIRYANI,
    price: 399,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    description: 'Richly flavored mutton biryani cooked with exotic spices and saffron.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium'
  },
  {
    id: '8',
    name: 'Butter Chicken',
    category: Category.GRAVY,
    price: 289,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    description: 'Tender chicken cooked in a creamy tomato sauce with butter and fenugreek.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Mild'
  },
  {
    id: '9',
    name: 'Apollo Fish',
    category: Category.STARTERS,
    price: 259,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    description: 'Spicy deep-fried fish fillets tossed in a special masala yogurt sauce.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '10',
    name: 'Golden Prawn Fry',
    category: Category.FRIED,
    price: 329,
    image: 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&w=800&q=80',
    description: 'Crispy marinated prawns fried to golden perfection with curry leaves.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Medium',
    discount: 15
  },
  {
    id: '11',
    name: 'Chicken Shawarma Roll',
    category: Category.ROLLS,
    price: 149,
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80',
    description: 'Grilled chicken strips wrapped in pita bread with garlic mayo and veggies.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Mild'
  },
  {
    id: '12',
    name: 'Mega Meat Platter',
    category: Category.COMBOS,
    price: 1299,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    description: 'Assortment of Tandoori Chicken, Seekh Kebabs, and Fish Tikka. Serves 3-4.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Medium',
    discount: 50
  },
  {
    id: '13',
    name: 'Chicken Lollipop',
    category: Category.STARTERS,
    price: 229,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    description: 'Frenched chicken winglet marinated in red spices and deep-fried.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Spicy'
  },
  {
    id: '14',
    name: 'Chettinad Chicken Curry',
    category: Category.GRAVY,
    price: 269,
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
    description: 'Fiery chicken curry from the Chettinad region made with roasted spices and coconut.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '15',
    name: 'Grilled Tandoori Chicken',
    category: Category.STARTERS,
    price: 349,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    description: 'Whole chicken legs marinated in yogurt and spices, roasted in a clay oven.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium'
  },
  {
    id: '16',
    name: 'Nellore Fish Curry',
    category: Category.GRAVY,
    price: 329,
    image: 'https://images.unsplash.com/photo-1601000938259-9e92002320b2?auto=format&fit=crop&w=800&q=80',
    description: 'Tangy and spicy fish curry made with tamarind and traditional spices.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '17',
    name: 'Tandoori Pomfret',
    category: Category.STARTERS,
    price: 499,
    image: 'https://images.unsplash.com/photo-1535568841029-28cb6aa80f76?auto=format&fit=crop&w=800&q=80',
    description: 'Whole pomfret marinated in yogurt and tandoori spices, grilled to perfection.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium'
  },
  {
    id: '18',
    name: 'Special Prawn Biryani',
    category: Category.BIRYANI,
    price: 379,
    image: 'https://images.unsplash.com/photo-1599020792689-9fde458e7e17?auto=format&fit=crop&w=800&q=80',
    description: 'Flavorful basmati rice cooked with marinated prawns and secret spices.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Medium',
    discount: 10
  },
  {
    id: '19',
    name: 'Kerala Fish Fry',
    category: Category.FRIED,
    price: 289,
    image: 'https://images.unsplash.com/photo-1626077309990-28564f89fb03?auto=format&fit=crop&w=800&q=80',
    description: 'Seer fish slices marinated in spicy paste and shallow fried in coconut oil.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '20',
    name: 'Butter Garlic Prawns',
    category: Category.STARTERS,
    price: 349,
    image: 'https://images.unsplash.com/photo-1535400255456-984241443b29?auto=format&fit=crop&w=800&q=80',
    description: 'Juicy prawns sautéed in rich butter and garlic sauce.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Mild',
    discount: 10
  },
  {
    id: '21',
    name: 'Mutton Seekh Kebab',
    category: Category.STARTERS,
    price: 389,
    image: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?auto=format&fit=crop&w=800&q=80',
    description: 'Minced mutton mixed with spices and grilled on skewers until charred and juicy.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    discount: 5
  },
  {
    id: '22',
    name: 'Tangdi Kebab',
    category: Category.STARTERS,
    price: 299,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    description: 'Chicken drumsticks marinated in yogurt and spices, roasted in tandoor.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Mild'
  },
  {
    id: '23',
    name: 'Andhra Chicken Curry',
    category: Category.GRAVY,
    price: 279,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    description: 'Spicy chicken curry made with green chilies, curry leaves, and traditional spices.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '24',
    name: 'Goan Fish Curry',
    category: Category.GRAVY,
    price: 339,
    image: 'https://images.unsplash.com/photo-1626509683526-25cb48df7409?auto=format&fit=crop&w=800&q=80',
    description: 'Tangy and spicy fish curry made with coconut milk and kokum.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    discount: 10
  },
  {
    id: '25',
    name: 'Nethili Fish Fry',
    category: Category.FRIED,
    price: 229,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
    description: 'Crispy deep-fried anchovies coated in spicy masala. A perfect snack.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Spicy'
  },
  {
    id: '26',
    name: 'Dragon Chicken',
    category: Category.FRIED,
    price: 269,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    description: 'Chicken strips tossed in spicy red sauce with cashews and bell peppers.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Spicy',
    discount: 15
  },
  {
    id: '27',
    name: 'Double Egg Roll',
    category: Category.ROLLS,
    price: 89,
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80',
    description: 'Two eggs beaten and fried on paratha with onions, chillies, and sauces.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Mild'
  },
  {
    id: '28',
    name: 'Mutton Keema Roll',
    category: Category.ROLLS,
    price: 189,
    image: 'https://images.unsplash.com/photo-1606728035253-49e8a23146de?auto=format&fit=crop&w=800&q=80',
    description: 'Spicy minced mutton sautéed and wrapped in flaky paratha.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Spicy'
  },
  {
    id: '29',
    name: 'Chicken Bucket Biryani',
    category: Category.COMBOS,
    price: 1499,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    description: 'Family pack serves 5-6. Includes Chicken 65, Eggs, Raitha, and Gravy.',
    isAvailable: true,
    isBestseller: true,
    spiceLevel: 'Medium',
    discount: 20
  },
  {
    id: '30',
    name: 'Seafood Platter',
    category: Category.COMBOS,
    price: 1899,
    image: 'https://images.unsplash.com/photo-1599458253896-76497f88f7bc?auto=format&fit=crop&w=800&q=80',
    description: 'Assortment of Grilled Prawns, Fish Tikka, Crispy Calamari, and Crab Lollipop.',
    isAvailable: true,
    isBestseller: false,
    spiceLevel: 'Medium',
    discount: 30
  }
];